### ISSUE TITLE
使用langchain接入chatgpt输出没有内容

### ISSUE THREAD

**Issue by 1148514800** [datawhalechina/llm-universe#110]
结果显示有tokens，却看不见具体内容
content='' response_metadata={'token_usage': {'completion_tokens': 41, 'prompt_tokens': 95, 'total_tokens': 136}, 'model_name': 'gpt-3.5-turbo', 'system_fingerprint': None, 'finish_reason': 'content_filter', 'logprobs': None} id='run-28d73283-36c7-4a3e-afbc-d4652bed3bd2-0'

from langchain.prompts.chat import ChatPromptTemplate

template = "你是一个翻译助手，可以帮助我将 {input_language} 翻译成 {output_language}."
human_template = "{text}"

chat_prompt = ChatPromptTemplate.from_messages([
    ("system", template),
    ("human", human_template),
])

text = "我带着比身体重的行李，\
游入尼罗河底，\
经过几道闪电 看到一堆光圈，\
不确定是不是这里。\
"
messages  = chat_prompt.format_messages(input_language="中文", output_language="英文", text=text)
print(messages) # [SystemMessage(content='你是一个翻译助手，可以帮助我将 中文 翻译成 英文.'), HumanMessage(content='我带着比身体重的行李，游入尼罗河底，经过几道闪电 看到一堆光圈，不确定是不是这里。')]

output = llm.invoke(messages)

print(output)

**Comment by logan-zou** [comment]
请问打印的 output 是什么？空吗？

**Comment by 1148514800** [comment]
> 请问打印的 output 是什么？空吗？

对的，打印出来的内容为空

**Comment by xuhu0115** [comment]
我测试了下，仓库里的代码目前是没问题的，检查下API是否可用，其他内容是否能正常输出呢？刷新下，换个窗口试试

**Comment by SummCoder** [comment]
看打印出来的结果中有'finish_reason': 'content_filter'而不是'finish_reason': 'stop'可能是返回的内容被过滤掉了？

**Comment by xuhu0115** [comment]
> 看打印出来的结果中有'finish_reason': 'content_filter'而不是'finish_reason': 'stop'可能是返回的内容被过滤掉了？

有可能，你用的是openai官方的API吗？把text内容替换成个简单的测试下呢

**Comment by logan-zou** [comment]
时间较长没有反馈，关闭此issue
