### ISSUE TITLE
在使用nltk时，出现每次都要重新下载package averaged_perceptron_tagger或者Connection refused问题

### ISSUE THREAD

**Issue by Dewwwww** [datawhalechina/llm-universe#111]
[nltk_data] Error loading averaged_perceptron_tagger: <urlopen error
[nltk_data]     [Errno 61] Connection refused>
[nltk_data] Error loading averaged_perceptron_tagger: <urlopen error
[nltk_data]     [Errno 61] Connection refused>
[nltk_data] Error loading averaged_perceptron_tagger: <urlopen error
[nltk_data]     [Errno 61] Connection refused>
[nltk_data] Error loading averaged_perceptron_tagger: <urlopen error
[nltk_data]     [Errno 61] Connection refused>
在挂代理之后该问题解决了，但出现以下问题，会一直提示重新更新
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /Users/yaoyi/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /Users/yaoyi/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /Users/yaoyi/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /Users/yaoyi/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!

**Comment by logan-zou** [comment]
您好，可以参考C1第三节将 nltk 资源包手动下载到本地，则不会再重新自动下载并引发网络问题
