### ISSUE TITLE
请问我在使用API开发应用那章，想要用智谱的api key，运行代码显示如下图错误，但是我用的apikey是用.分割的，不知为什么？

### ISSUE THREAD

**Issue by klayc-gzl** [datawhalechina/llm-universe#117]

**Comment by klayc-gzl** [comment]
是直接在llm-universe文件夹中的.env输入apikey就可以吗，我发现它好像没有载入.env文件里的信息：
![image](https://github.com/datawhalechina/llm-universe/assets/80515849/5451088a-e5df-45c4-b04f-fdbba11b4ccc)
![image](https://github.com/datawhalechina/llm-universe/assets/80515849/ca9756d5-704a-43f2-ab70-b17d2826b2f0)

**Comment by klayc-gzl** [comment]
是直接在llm-universe文件夹中的.env输入apikey就可以吗，我发现它好像没有载入.env文件里的信息：
image
![image](https://github.com/datawhalechina/llm-universe/assets/80515849/a2cbd1e0-2c2a-4340-a574-5fd0b5357f1c)

**Comment by ZhaiYanbo** [comment]
我也是，请问解决了吗？
