### ISSUE TITLE
C3 词向量及向量知识库 文本是否有歧义

### ISSUE THREAD

**Issue by machenme** [datawhalechina/llm-universe#120]
在机器学习和自然语言处理（NLP）中，词向量（Embeddings）是一种将非结构化数据，如单词、句子或者整个文档，转化为实数向量的技术。这些实数向量可以被计算机更好地理解和处理。

嵌入背后的主要想法是，相似或相关的对象在嵌入空间中的距离应该很近

嵌入背后 是指什么嵌入呢.或者说其实是想描述 词向量的主要想法

**Comment by lta155** [comment]
向量及嵌入都是根据embedding翻译而来，嵌入背后确实是指词向量的主要想法，很抱歉给您造成困惑，我将在后续更改这一错误
