### ISSUE TITLE
添加Embedding API 例子 - 阿里云DashVector

### ISSUE THREAD

**Issue by sosyz** [datawhalechina/llm-universe#130]
[阿里云向量检索服务](https://help.aliyun.com/document_detail/2510274.html?spm=a2c4g.2510317.0.0.66862238kdulT1)

有意向的话可以分配给我～

**Comment by logan-zou** [comment]
抱歉，由于目前团队正全力准备 RAG 进阶部分，暂不考虑更新该部分内容~
