### ISSUE TITLE
jupyter notebook运行某些单元格的时候一直卡在[*]这样的状态是正常的吗，尤其是加载某些文件的时候，pdf还正常，markdown就加载不出来了

### ISSUE THREAD

**Issue by SparkandAurora** [datawhalechina/llm-universe#135]

**Comment by logan-zou** [comment]
这个问题应该是机器内存受限或者是服务器远程连接问题，建议更换机器测试

**Comment by SparkandAurora** [comment]
明白 谢谢您！

---- 回复的原邮件 ----
| 发件人 | Logan ***@***.***> |
| 发送日期 | 2024年09月15日 11:12 |
| 收件人 | datawhalechina/llm-universe ***@***.***> |
| 抄送人 | SparkandAurora ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [datawhalechina/llm-universe] jupyter notebook运行某些单元格的时候一直卡在[*]这样的状态是正常的吗，尤其是加载某些文件的时候，pdf还正常，markdown就加载不出来了 (Issue #135) |

这个问题应该是机器内存受限或者是服务器远程连接问题，建议更换机器测试
