### ISSUE TITLE
notebook/C7 高级 RAG 技巧/2. 数据处理/1.多类型文档处理.ipynb 中遇到nltk问题

### ISSUE THREAD

**Issue by SwallowData** [datawhalechina/llm-universe#137]

**Comment by lta155** [comment]
有部分同学在第一部分内容碰到过这个问题，可以尝试下方链接的方法解决
https://github.com/datawhalechina/llm-universe/blob/4182b48827947a4d95453f88d3b01478a9548e39/docs/C1/7.%E7%8E%AF%E5%A2%83%E9%85%8D%E7%BD%AE.md#31-%E4%B8%8B%E8%BD%BD-nltk-%E7%9B%B8%E5%85%B3%E8%B5%84%E6%BA%90
