### ISSUE TITLE
通用环境配置问题

### ISSUE THREAD

**Issue by ZmjjKKhub** [datawhalechina/llm-universe#139]
在希望存储项目的路径下克隆当前仓库时，提示
The authenticity of host 'github.com (140.82.113.4)' can't be established.
ECDSA key fingerprint is SHA256:p2QAMXNIC1TJYWeIOttrVc98/R1BUFWu3/LiyKgUfQM.
Are you sure you want to continue connecting (yes/no/[fingerprint])? fingerprint
Please type 'yes', 'no' or the fingerprint: SHA256:p2QAMXNIC1TJYWeIOttrVc98/R1BUFWu3/LiyKgUfQM
Warning: Permanently added 'github.com,140.82.113.4' (ECDSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
想问下作者这个是什么原因？

**Comment by logan-zou** [comment]
这个应该是git权限问题，看看是不是个人机器上没有放 git 密钥
