### ISSUE TITLE
api部分，星火版本更新，千帆系统更新

### ISSUE THREAD

**Issue by Analalaa** [datawhalechina/llm-universe#140]

**Comment by Analalaa** [comment]
![image](https://github.com/user-attachments/assets/c66b3a94-ae82-4184-a30e-173ef2d04016)

**Comment by Analalaa** [comment]
![image](https://github.com/user-attachments/assets/54f88cf7-8461-486a-b5a9-8e7e61af22c8)
没有version如文档所示咧

**Comment by logan-zou** [comment]
已更新
