### ISSUE TITLE
C7高级RAG技巧-2.数据处理-train_dataset.json的生成问题

### ISSUE THREAD

**Issue by ajione** [datawhalechina/llm-universe#145]
请问大佬，这个train_dataset.json生成是人工标记还是用“文段自动生成问题”来自动生成的

**Comment by lta155** [comment]
是运行[generate_qa_pairs.py](https://github.com/datawhalechina/llm-universe/blob/main/notebook/C7%20%E9%AB%98%E7%BA%A7%20RAG%20%E6%8A%80%E5%B7%A7/2.%20%E6%95%B0%E6%8D%AE%E5%A4%84%E7%90%86/generate_qa_pairs.py)自动生成的，调用的glm-4-plus，具体细节可以从链接中看到。

**Comment by ajione** [comment]
谢谢大佬，运行成功了，只不过由于prompt的问题导致回复格式不稳定，我添加了“严格按照以下”的prompt，让回答格式稳定了。

**Comment by lta155** [comment]
嗯呐嗯呐，很高兴能帮到你
