### ISSUE TITLE
依赖安装失败

### ISSUE THREAD

**Issue by NanshineLoong** [datawhalechina/llm-universe#21]
在windows下运行
`pip install -r requirements_windows.txt`
或者
`pip install -r requirements.txt`
都不能成功安装依赖
前者会卡在找不到backports=1.0这个包
![image](https://github.com/datawhalechina/llm-universe/assets/100546876/0f22faa0-4122-4f96-a565-c79f5189cba4)
后者会卡在uviloop这个包不能适配windows系统

**Comment by logan-zou** [comment]
使用requirements_windows无法安装，可能是因为镜像网站问题，试试针对失败的包切换镜像源（例如清华源、官网源）
