### ISSUE TITLE
第二课第五小节“调用智谱API”部分模型名称变更

### ISSUE THREAD

**Issue by linzeyang** [datawhalechina/llm-universe#22]
智谱 AI 开放平台目前已主推 `chatglm_turbo` 模型，且 pro、std、lite 模型将于2023年11月底下线。

建议将课程中涉及到模型名称的部分（如代码中的 `model = "chatglm_std"`）改为 `chatglm_turbo`。

如图：
![screenshot-open bigmodel cn-2023 11 15-23_39_16](https://github.com/datawhalechina/llm-universe/assets/4020306/671b7cc3-de12-4de1-a69e-dcffbb4e9a7c)
![screenshot-open bigmodel cn-2023 11 15-23_39_39](https://github.com/datawhalechina/llm-universe/assets/4020306/a7647bdd-c381-4cc8-afdf-e6350ee8d026)

**Comment by logan-zou** [comment]
已更新
