### ISSUE TITLE
Dimensionality of (1024) does not match index dimensionality (1536)

### ISSUE THREAD

**Issue by kaka2008** [datawhalechina/llm-universe#33]
使用zhipuai，初始化知识库，点击chat db without history，提示Dimensionality of (1024) does not match index dimensionality (1536)

我知道zhipuai返回的向量维度是1024，在哪里修改chroma的维度？

**Comment by logan-zou** [comment]
该问题可能是因为在项目中同时使用了zhipu和openai的embedding，如果使用zhipuai初始化知识库，请确认调用时使用的是zhipuai的embedding
