### ISSUE TITLE
embeding后维度不一致问题。

### ISSUE THREAD

**Issue by edandong108** [datawhalechina/llm-universe#44]
你好.我在做向量数据库时，采用了智普的大模型做embedding，在写入choram向量数据库时，因为向量化后的维度不一致导致无法写入。查了很久不知道怎么解决。请大神指点
![066265eef82c57a136caa6ed8fe4886](https://github.com/datawhalechina/llm-universe/assets/156925796/5db864f4-5312-4ba7-b4f1-e73db6818301)
![b8e3395875b1b56886b1b920a3f24d4](https://github.com/datawhalechina/llm-universe/assets/156925796/8b7cd7c5-9693-45e9-8fb8-656de5d10fa8)

**Comment by logan-zou** [comment]
不好意思现在才回复你，我们没有在构建知识库的时候出现该问题，如目前仍然存在该问题，欢迎给我发邮件
