### ISSUE TITLE
zhipuai_embedding 包不存在，不能安装，也没说明去哪里获取

### ISSUE THREAD

**Issue by An-Jhon** [datawhalechina/llm-universe#46]
`from zhipuai_embedding import ZhipuAIEmbeddings`
想问一下 zhipuai_embedding 这个包在哪里获取啊，也没说怎么获取呀

**Comment by logan-zou** [comment]
您好，这个是我们自定义的代码，可以 clone 项目代码使用：https://github.com/datawhalechina/llm-universe/blob/main/notebook/C2%20%E8%B0%83%E7%94%A8%E5%A4%A7%E6%A8%A1%E5%9E%8B%20API/zhipuai_embedding.py
