### ISSUE TITLE
这个gradio的版本号是不是不对？

### ISSUE THREAD

**Issue by shaoqiming** [datawhalechina/llm-universe#51]
![image](https://github.com/datawhalechina/llm-universe/assets/12133970/3e74e8b8-caa3-4a8f-a1fb-ffd325428613)

![image](https://github.com/datawhalechina/llm-universe/assets/12133970/405f0723-df04-4ec0-9d4f-161aa49eded1)

代码中的gradio 版本号是4.3.0   但是pip的仓库中没有这个的版本号吧

**Comment by shaoqiming** [comment]
这个截图的 是我已经修改过的。但是在仓库里面的是 4.3.0

**Comment by logan-zou** [comment]
目前我们已更新第二版，环境依赖也已经更新，欢迎体验
