### ISSUE TITLE
在 6. 调用智谱 AI(ChatGLM)生成 embedding 中，调用API时报错：module ‘’zhipuai‘ has no attribute ‘model api’

### ISSUE THREAD

**Issue by ElisiaZ** [datawhalechina/llm-universe#52]
![1711102440277](https://github.com/datawhalechina/llm-universe/assets/152286060/7a2251f5-2012-4205-b085-986e83ddea5a)

**Comment by 33wyd** [comment]
+1 同样遇到了这个问题不知道应该怎么解决

**Comment by logan-zou** [comment]
您好，这个问题应该是版本导致的，可以 check 一下 zhupuai 的版本和 requirements 是否一致
