### ISSUE TITLE
更新后的版本

### ISSUE THREAD

**Issue by WangHaoyuuu** [datawhalechina/llm-universe#60]
您好，特别感谢你们的项目，请问一下目前我是安装1.0版本学习的，学习完后可以无缝衔接到2.x吗

**Comment by logan-zou** [comment]
您好，新版本主要是针对之前学习者反馈的环境问题、难度问题进行了修正，如果您已经完成 1.0版本的学习，不需要重新学习 2.x 版本，大部分内容是一致的，只是针对 api 进行了更新以及调整了难度；我们很快将会推出第二部分 RAG 进阶技巧，欢迎届时阅读学习～

**Comment by WangHaoyuuu** [comment]
谢谢
