### ISSUE TITLE
更新后的版本会有project吗

### ISSUE THREAD

**Issue by WangHaoyuuu** [datawhalechina/llm-universe#62]
您好，非常感谢你们的项目，想请问一下更新后的版本会有project吗

**Comment by lta155** [comment]
有的有的，后期可以在readme看到

**Comment by logan-zou** [comment]
为了调节学习难度，新版本不再放 project，所有代码均直接在 notebook 中实现；原版 project 在升级之后目前存放在新地址：https://github.com/logan-zou/Chat_with_Datawhale_langchain，目前还在更新，欢迎查看

**Comment by WangHaoyuuu** [comment]
好的！我看到新版本的是使用的Streamlit，想请问一下会实现支持保持对话记录吗？即类似chatgpt左侧的history。[Streamlit](https://streamlit.io/)

**Comment by xuhu0115** [comment]
> 好的！我看到新版本的是使用的Streamlit，想请问一下会实现支持保持对话记录吗？即类似chatgpt左侧的history。[Streamlit](https://streamlit.io/)

你提到的ChatGPT 左侧的对话历史记录这部分功能，涉及到后端的数据保存，需要将会话 ID 会与用户的账户关联起来，目前项目组还没考虑这方面的更新，感兴趣的话可以与后端的小伙伴讨论一下！

**Comment by WangHaoyuuu** [comment]
嗯嗯！好的谢谢
