### ISSUE TITLE
第四课 “向量数据库” 部分的代码错误

### ISSUE THREAD

**Issue by linzeyang** [datawhalechina/llm-universe#8]
在 [课程文档](https://github.com/datawhalechina/llm-universe/blob/d322a14ff710a80589a4945b2bfc419fdab553bb/docs/C4/2.%20%E5%90%91%E9%87%8F%E6%95%B0%E6%8D%AE%E5%BA%93%E7%9A%84%E4%BB%8B%E7%BB%8D%E5%8F%8A%E4%BD%BF%E7%94%A8.md?plain=1#L239) 和 [notebook](https://github.com/datawhalechina/llm-universe/blob/d322a14ff710a80589a4945b2bfc419fdab553bb/notebook/C4%20%E6%95%B0%E6%8D%AE%E5%BA%93%E6%90%AD%E5%BB%BA/2.%20%E5%90%91%E9%87%8F%E6%95%B0%E6%8D%AE%E5%BA%93%E7%9A%84%E4%BB%8B%E7%BB%8D%E5%8F%8A%E4%BD%BF%E7%94%A8.ipynb#L408) 中 ChatGLM2 的模型 ID 有错误，应为
```python
model_id = 'THUDM/chatglm2-6b'
```

在 [课程文档](https://github.com/datawhalechina/llm-universe/blob/d322a14ff710a80589a4945b2bfc419fdab553bb/docs/C4/2.%20%E5%90%91%E9%87%8F%E6%95%B0%E6%8D%AE%E5%BA%93%E7%9A%84%E4%BB%8B%E7%BB%8D%E5%8F%8A%E4%BD%BF%E7%94%A8.md?plain=1#L241) 和 [notebook](https://github.com/datawhalechina/llm-universe/blob/d322a14ff710a80589a4945b2bfc419fdab553bb/notebook/C4%20%E6%95%B0%E6%8D%AE%E5%BA%93%E6%90%AD%E5%BB%BA/2.%20%E5%90%91%E9%87%8F%E6%95%B0%E6%8D%AE%E5%BA%93%E7%9A%84%E4%BB%8B%E7%BB%8D%E5%8F%8A%E4%BD%BF%E7%94%A8.ipynb#L410) 中参数 `trust_remote_code` 传入有错误，应为
```python
model = AutoModel.from_pretrained(model_id, trust_remote_code=True).half().quantize(4).cuda()
```

另外，建议模型直接选择 `chatglm2-6b-int4`，可节省硬盘占用以及实时量化所需的运算资源。

**Comment by 0-yy-0** [comment]
感谢您的 issus 我们已经进行了相应的修改
