### ISSUE TITLE
求助：星火API调用Bug

### ISSUE THREAD

**Issue by Explorer-Dong** [datawhalechina/llm-universe#82]
文档中关于星火 api 调用的示例很简洁，但是有一个问题就是，下方的 `sparkAPI.main` 函数的返回值是 `None`，这个 `response` 是无效的。那么应该如何流式的获得响应的数据并且封装好呢 :)
![image](https://github.com/datawhalechina/llm-universe/assets/128051718/b7f00378-8c4b-48ab-93e8-af24ae1af3b1)

**Comment by Myoungs** [comment]
你好，#1  `sparkAPI.main` 函数的返回值是 `None`：麻烦检查一下环境变量是否正确的设置和加载了，如还有问题，可以提供更多的信息辅助排查；#2 最新的 pr 里补充了星火 sdk 的调用方式，可以通过设置 `streaming=True` 来实现流式调用，课程中暂不涉及

**Comment by Explorer-Dong** [comment]
感谢！问题已解决 😃
