### ISSUE TITLE
默认版本的千帆模型不能准确检查2.1.3中给出的prompt是否满足条件

### ISSUE THREAD

**Issue by Atoc0** [datawhalechina/llm-universe#89]
2.1.3中强制要求他总结的话可以总结成要求的格式,但是给他判断后就判断为不满足了,按照流程调用默认版本的智谱可以哈哈

**Comment by Myoungs** [comment]
感谢反馈～2.1.3 的示例是使用 openai 接口完成的，不同模型的效果可能存在差异
